// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List employees
	// (GET /employees)
	ListEmployees(c *gin.Context, params ListEmployeesParams)
	// Creates a new employee
	// (POST /employees)
	AddEmployee(c *gin.Context)
	// Cancel a day off request
	// (POST /employees/day-offs/{id}/cancel)
	CancelDayOff(c *gin.Context, id int64)
	// Deletes a employee by ID
	// (DELETE /employees/{id})
	DeleteEmployee(c *gin.Context, id int64)
	// Returns a employee by ID
	// (GET /employees/{id})
	FindEmployeeByID(c *gin.Context, id int64)
	// Updates a employee
	// (PUT /employees/{id})
	UpdateEmployee(c *gin.Context, id int64)
	// List day off records
	// (GET /employees/{id}/day-offs)
	ListDayOffs(c *gin.Context, id int64, params ListDayOffsParams)
	// Submit a day off request
	// (POST /employees/{id}/day-offs)
	SubmitDayOff(c *gin.Context, id int64)

	// (GET /liveness)
	GetLiveness(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListEmployees operation middleware
func (siw *ServerInterfaceWrapper) ListEmployees(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEmployeesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", c.Request.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sortBy: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortOrder", c.Request.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sortOrder: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "filters" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "filters", c.Request.URL.Query(), &params.Filters)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filters: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListEmployees(c, params)
}

// AddEmployee operation middleware
func (siw *ServerInterfaceWrapper) AddEmployee(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddEmployee(c)
}

// CancelDayOff operation middleware
func (siw *ServerInterfaceWrapper) CancelDayOff(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelDayOff(c, id)
}

// DeleteEmployee operation middleware
func (siw *ServerInterfaceWrapper) DeleteEmployee(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteEmployee(c, id)
}

// FindEmployeeByID operation middleware
func (siw *ServerInterfaceWrapper) FindEmployeeByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FindEmployeeByID(c, id)
}

// UpdateEmployee operation middleware
func (siw *ServerInterfaceWrapper) UpdateEmployee(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateEmployee(c, id)
}

// ListDayOffs operation middleware
func (siw *ServerInterfaceWrapper) ListDayOffs(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDayOffsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", c.Request.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sortBy: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortOrder", c.Request.URL.Query(), &params.SortOrder)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sortOrder: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "startTimeFrom" -------------

	err = runtime.BindQueryParameter("form", true, false, "startTimeFrom", c.Request.URL.Query(), &params.StartTimeFrom)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter startTimeFrom: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "startTimeTo" -------------

	err = runtime.BindQueryParameter("form", true, false, "startTimeTo", c.Request.URL.Query(), &params.StartTimeTo)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter startTimeTo: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "filters" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "filters", c.Request.URL.Query(), &params.Filters)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filters: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDayOffs(c, id, params)
}

// SubmitDayOff operation middleware
func (siw *ServerInterfaceWrapper) SubmitDayOff(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitDayOff(c, id)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLiveness(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/employees", wrapper.ListEmployees)
	router.POST(options.BaseURL+"/employees", wrapper.AddEmployee)
	router.POST(options.BaseURL+"/employees/day-offs/:id/cancel", wrapper.CancelDayOff)
	router.DELETE(options.BaseURL+"/employees/:id", wrapper.DeleteEmployee)
	router.GET(options.BaseURL+"/employees/:id", wrapper.FindEmployeeByID)
	router.PUT(options.BaseURL+"/employees/:id", wrapper.UpdateEmployee)
	router.GET(options.BaseURL+"/employees/:id/day-offs", wrapper.ListDayOffs)
	router.POST(options.BaseURL+"/employees/:id/day-offs", wrapper.SubmitDayOff)
	router.GET(options.BaseURL+"/liveness", wrapper.GetLiveness)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ3W4UuRJ+FcvnXJwjNZmBRQiNxAVkgM2CSJSEK3YuKu3qGbNuu7HdCbPRvPvK1f/T",
	"nglByW7EcpVM2y5X1ffVX/c1T01eGI3aOz675i5dYQ707xzWx1l2iqmxIvwurCnQeom0Kmj1fF1g+IW6",
	"zPnsEz85P+YJdzL9gymES+QJL8Ci9qDaBxdow385as8XCfckgjtvpV7yTcIxL5RZIx7N6R50qZWFl0bz",
	"Gf+o5ZcSmRTMZMyvkDWbecIzY3PwfMal9s+e8oTnUss86PW4vUVqj0u0dI0W5zIn7duTAjw+8uFpRC+L",
	"4IIS1+Ml58H620gjcV9KaVEEt/VMTvqebS/tX9Gp3nnPXHzG1AdVXjcOmV1zUOo447NP1/y/FjM+4/+Z",
	"dGhPaqgnH/CqPbRJtnGW4h5R2HKDFHyxWQQjrDV2zLnUCBxrQ5sZrcVwztE5WO481yzfBFEtv9ketHwv",
	"na+CxJ2iK4x2GIsTD+RHjzk92AfFIOQ2rUpgLazD7yJqyGFpQ4ixsMp0mV+gvZH9Ye+Z/DMi7QMJCMiS",
	"yqxAS5JvFOmNB3VoSu3HQs/DWq1bEG3JRLeXL9Mb+UK+HVxcu6hnXyxGAnAN5e8Kul4I/YTtfmDrJ6oR",
	"WCCEReei6VlgAdZTwenVqjNQGEx5IzXoVILiCZ+jk8uQbl/rpdSIJCHhb1GjBcUgy0Bat6NsgVSD/F89",
	"iWzVkMcQhBwjCXV02ugLA1bMwY/LTWx/sTIaK3rEixcosOuwdAsMyYSkNbF/R9Ji0coeKj0AJCTSE6OX",
	"Y0QHRXV/cu62jnkT9kqdmbHDXzKHVqILTn95cuRYZiz79ZSdrR1FfMK99CrIGjy8ROsqAY8PpgdTgqRA",
	"DYXkM/4LPQpE9iuyYtJASb+WGImyU/RW4iUyCBErNXgUTEnng2LtcXYl/YplUnliJQMtmDPWh/8NiQrK",
	"BQdC+HEk+GyY6KpeDHL0aB11BTLc/qVEQqgiZROIVVqrdM2gVJ6yx/5avlsghXRc6DThOXytpU6n33dH",
	"8MOr9eCGJsq3iNpj3pCUi0gDsPuyYyuI6RGLOLiUerTq/upXAHzHFUMuvMP1o0tQJbIiZBqiZId5nX/Z",
	"//BgeZDUC+5TZ9TiRS9x/V5Op0+eNZuC9osXv5mV/n9Q72uhqJvytsQkamd9cGAlCCGDpqBOBrE6Siqj",
	"5O38mkJJIBbH9dNFiOKq+pKUJ9Np1eZpX+dqKAolUyL05HPdfXfa7KvH8RpP2WDo8eN3VYmo4buj66sO",
	"NnJdqfFrgWkIcaz3JNyVeU45mCK2i3lK38ZFcsahRfDoGDCNV+0BJjWVD0fJ6oDNy0p/FCyA6hhYZKCU",
	"uUIxShYvhXjdlZ2QXtH5V0as78wpg0lj7JrWCm8YCBH+dMbwfsYPpN3cI3n2afmw+BLnAW3qKs9EwPqR",
	"yTI3uZZiM0lBp0itSsOtIREOab2aRXYUjVDeukwhxQidftIY9YqjtL74fr5tTYikuqLNp7vm9e3Jbnwm",
	"3kV8E/+G6M1hzUwWGmeyjtV3oWCuTFN0LiuVWj8oQpGGDJgYqr5NqcCkyl6FPtLNVs8DMZ3US9W1tOwC",
	"HApmqkx1NGeuDEZGEtKcRPRy0hYThxcezfvtUkgetWrJ/VF2AP/TXU4QDwnfeYtLB8iaHc2Djru609Lq",
	"4YEGwRZcenE1RO+N1G09ebWmDbfA725Q29tLLn4WkB3wNnwoyggfPhbi5s5jxIbq1PfF8t/FhX+04SnJ",
	"QUM3/ux5opTtGLir36E2p2l6enP3eDqu398+OEImP/Z03k3Lw+8a1czcf9b7GnJ3IzqN47eY0aN3NEq+",
	"sSbnUaTjb+RuFHhubivuLt4htH5evDg5P/7XvCPY/oATSUfv61dxXUdcvQV/aK8NIvrFB7yz8iKXfteA",
	"92OW4uGntW8Z5x7f4937p0RH+PgHPCVWDNo1JSp5ibr+GBOtvG/Rv2/23GN803eFiHGNfsz2op4MRHvZ",
	"hEFpFZ/xlffFbDJRJgW1Ms7Pnk+fT/lmsfkrAAD//6BnMWY5IQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
